### ISSUE TITLE
DeckTrendsPage

### ISSUE THREAD

**Issue by kocetora** [procrastine-inc/procrastine-inc-hsmeta#1]
"decks":"name": "Grim Patron Warrior",
"decks":"rank": {
"last": [1,1,1,1,2,1,1,1,3,9,10,0],
"current": 1
}
"decks":"tier"

**Comment by vermi4elli** [comment]
The parameter should look like this, I guess

> %7b%22decks%22:%22name%22:%22Grim Patron Warrior%22,%22decks%22:%22rank%22:%7b%22last%22:%5b1,1,1,1,2,1,1,1,3,9,10,0%5d,%22current%22:1%7d%22decks%22:%22tier%22%7d

**Comment by vermi4elli** [comment]
Ah, that's unfortunate, I would try to find a correct way
![image](https://user-images.githubusercontent.com/42549298/103158104-eff57300-47c2-11eb-8b2d-2e2ec10ffa7d.png)

**Comment by kocetora** [comment]
Try this one https://tempostorm.com/api/snapshots/?where=%7B%22snapshotType%22:%22standard%22%7D
