### ISSUE TITLE
Fetch for Deck data | DeckPage by TierN

### ISSUE THREAD

**Issue by kocetora** [procrastine-inc/procrastine-inc-hsmeta#5]
https://tempostorm.com/api/decks/findOne?filter=

```
{
  "where":{
    "slug":"etc-warrior-standard-meta-snapshot-dec-14-2020"
  },
  "fields":[
    "name",
    "description",
    "playerClass",
    "dust",
    "heroName",
    "deckType"
  ],
  "include":[{
    "relation":
        "cards",
        "scope":{
          "include":
            "card",
            "scope":{
              "fields":[
                "name",
                "name_ru",
                "cardType",
                "cost",
                "dust"
              ]
            }
        }
  }]
}
```

**Comment by vermi4elli** [comment]
This is the original request:

> https://tempostorm.com/api/snapshots/findOne?filter={"where":{"slug":"2020-12-14","snapshotType":"standard"},"include":[{"relation":"comments","scope":{"include":[{"relation":"author","scope":{"fields":["username","gravatarUrl"]}}],"order":"createdDate+DESC"}},{"relation":"deckMatchups","scope":{"include":[{"relation":"forDeck","scope":{"fields":["name","name_ru","playerClass"]}},{"relation":"againstDeck","scope":{"fields":["name","name_ru","playerClass"]}}]}},{"relation":"deckTiers","scope":{"include":[{"relation":"deck","scope":{"fields":["id","name","slug","playerClass"],"include":{"relation":"slugs","scope":{"fields":["linked","slug"]}}}},{"relation":"deckTech","scope":{"include":[{"relation":"cardTech","scope":{"include":[{"relation":"card","scope":{"fields":["name","name_ru","photoNames"]}}]}}]}}]}},{"relation":"authors","scope":{"include":[{"relation":"user","scope":{"fields":["username","social"]}}]}},{"relation":"votes","scope":{"fields":["direction","authorId"]}},{"relation":"slugs","scope":{"fields":["linked","slug"]}}]}

**Comment by vermi4elli** [comment]
This one is closer to the final result, but I don't really think it is the final:

> https://tempostorm.com/api/snapshots/findOne?filter={"where":{"slug":"2020-12-14","snapshotType":"standard"},"include":[{"relation":"deckTiers","scope":{"include":[{"relation":"deck","scope":{"fields":["id","name","slug","playerClass"],"include":{"relation":"slugs","scope":{"fields":["linked","slug"]}}}}]}}]}
